sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See invoke#358.
  allow_failures:
    - python: pypy3
  fast_finish: true
install:
  - pip install -r dev-requirements.txt
script:
  # TODO: tighten up these install test tasks so they can be one-shotted
  - inv test-installation --package=invocations --sanity="inv --list"
  - inv test-packaging --package=invocations --sanity="inv --list"
  - inv docs --nitpick
  - flake8
  - inv coverage --report=xml
# TODO: after_success -> codecov, once coverage sucks less XD
