sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See invoke#358.
  allow_failures:
    - python: pypy3
  fast_finish: true
install:
  # TODO: removeme
  - pip install -e git+https://github.com/bitprophet/pytest-relaxed
  - pip install -r dev-requirements.txt
script:
  - inv coverage --report=xml
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
