language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install -r dev-requirements.txt
script:
  - inv test
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
